### ISSUE TITLE
Firebase Terms of Service is not accepted. Navigate to your project's overview page on the Actions Console to accept the Terms of Service

### ISSUE THREAD

**Issue by luca-nardelli-memori** [actions-on-google/assistant-conversation-testing-nodejs#12] opened 2021-03-31 13:57 UTC
Closed in #4 , worked for 13 days, but today the error reappeared.

**Comment by Fleker** [comment] 2021-03-31 15:46
I'm going to close this as a duplicate of #4. Let's re-open that issue.

**Closed as completed by Fleker** 2021-03-31 15:46 UTC
