### ISSUE TITLE
Help (TypeError: Cannot use 'in' operator to search for 'endConversation' in undefined)

### ISSUE THREAD

**Issue by LuizPiresS** [actions-on-google/assistant-conversation-testing-nodejs#7] opened 2021-03-23 16:49 UTC
Good afternoon!!

I have one going through a little problem. Whenever I try to send the second query the error:
TypeError: Cannot use 'in' operator to search for 'endConversation' in undefined

```javascript
it('should trigger action', async function () {
    await test.sendQuery(TRIGGER_PHRASE);
    await test.sendQuery('Cartão Digital Pré-Pago')
    test.assertText('Parece que você está interessado em saber mais sobre cartões digitais pré-pagos! Como posso te ajudar? Você pode perguntar sobre o que é um cartão digital ou por onde você vai recebê-lo, por exemplo.')
  });

````
```error
--- sendQuery called with 'Falar com o app meu app de teste'
--- sendQuery called with 'Cartão Digital Pré-Pago'

TypeError: Cannot use 'in' operator to search for 'endConversation' in undefined
    at ActionsOnGoogleTestManager.getIsConversationEnded (node_modules\@assistant\conversation-testing\dist\action-on-google-test-manager.js:559:34)
    at ActionsOnGoogleTestManager.sendInteraction (node_modules\@assistant\conversation-testing\dist\action-on-google-test-manager.js:75:40)
    at ActionsOnGoogleTestManager.sendQuery (node_modules\@assistant\conversation-testing\dist\action-on-google-test-manager.js:68:21)
    at Context.<anonymous> (test\saldo.test.js:50:16)

```
Thank you very much

**Comment by Fleker** [comment] 2021-03-23 19:37
Closing as a duplicate of #6.

**Closed as completed by Fleker** 2021-03-23 19:37 UTC
